// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWmY1rzAlRZUfqLdDAn3QA-sKql6DjbIk',
    appId: '1:921146443622:web:2727f3b73f32f9f5bf6aa7',
    messagingSenderId: '921146443622',
    projectId: 'nako-car-service',
    authDomain: 'nako-car-service.firebaseapp.com',
    storageBucket: 'nako-car-service.firebasestorage.app',
    measurementId: 'G-KRZMTYJSXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9pNxHy96zGZEBM2P9Td9JjK3JHieBW4',
    appId: '1:921146443622:android:2f58ba841bec6dbcbf6aa7',
    messagingSenderId: '921146443622',
    projectId: 'nako-car-service',
    storageBucket: 'nako-car-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3VcncSBeocpwMN9Hw8aM8waC9erkqZI',
    appId: '1:921146443622:ios:ae11a0a4f377ac32bf6aa7',
    messagingSenderId: '921146443622',
    projectId: 'nako-car-service',
    storageBucket: 'nako-car-service.firebasestorage.app',
    iosBundleId: 'com.example.nakoCarService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3VcncSBeocpwMN9Hw8aM8waC9erkqZI',
    appId: '1:921146443622:ios:ae11a0a4f377ac32bf6aa7',
    messagingSenderId: '921146443622',
    projectId: 'nako-car-service',
    storageBucket: 'nako-car-service.firebasestorage.app',
    iosBundleId: 'com.example.nakoCarService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWmY1rzAlRZUfqLdDAn3QA-sKql6DjbIk',
    appId: '1:921146443622:web:c0d0630e10932a92bf6aa7',
    messagingSenderId: '921146443622',
    projectId: 'nako-car-service',
    authDomain: 'nako-car-service.firebaseapp.com',
    storageBucket: 'nako-car-service.firebasestorage.app',
    measurementId: 'G-MVL7CEB16F',
  );
}
